In [1]:
import warnings

warnings.filterwarnings('ignore')

In [2]:
# !pip3 install pyspark


In [3]:
import os
# Find the latest version of spark 3.0 from http://www.apache.org/dist/spark/ and enter as the spark version
# For example:
spark_version = 'spark-3.3.0'
os.environ['SPARK_VERSION']=spark_version

# Install Spark and Java
!apt-get update
!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!wget -q http://www.apache.org/dist/spark/$SPARK_VERSION/$SPARK_VERSION-bin-hadoop3.tgz
!tar xf $SPARK_VERSION-bin-hadoop3.tgz
!pip install -q findspark

# Set Environment Variables
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = f"/content/{spark_version}-bin-hadoop3"

# Start a SparkSession
import findspark
findspark.init()

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:5 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:12 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Fetched 252 kB in 3s (94.7 kB/s)
Reading package li

In [4]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sqlalchemy import create_engine

In [5]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from getpass import getpass
from pyspark.context import SparkContext
from pyspark.sql.session import SparkSession
from sqlalchemy import create_engine, Table, MetaData


In [6]:
!wget https://jdbc.postgresql.org/download/postgresql-42.2.16.jar

--2022-08-21 09:57:48--  https://jdbc.postgresql.org/download/postgresql-42.2.16.jar
Resolving jdbc.postgresql.org (jdbc.postgresql.org)... 72.32.157.228, 2001:4800:3e1:1::228
Connecting to jdbc.postgresql.org (jdbc.postgresql.org)|72.32.157.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1002883 (979K) [application/java-archive]
Saving to: ‘postgresql-42.2.16.jar.3’

postgresql-42.2.16. 100%[===================>] 979.38K  6.20MB/s    in 0.2s    

2022-08-21 09:57:48 (6.20 MB/s) - ‘postgresql-42.2.16.jar.3’ saved [1002883/1002883]



In [7]:
from getpass import getpass
password = getpass('Enter database password')
url = f"postgresql+psycopg2://postgres:{password}@jschelling0-challenge.cyw6xm1dnce5.us-west-1.rds.amazonaws.com/Arizona"

Enter database password··········


In [8]:
engine = create_engine(url)

In [9]:
df = pd.read_sql('SELECT * FROM  AZ_Annual_Average_Temps', engine)
#df = pd.read_sql_table('AZ_Annual_Average_Temps', engine)

# meta = MetaData()
#meta.reflect(engine)

In [10]:
df.head()

state  year  degrees_fahrenheit  anomaly
0    State  Year  Degrees Fahrenheit  Anomaly
1  Arizona  1970                  59     -0.8
2  Arizona  1971                58.2     -1.6
3  Arizona  1972                59.6     -0.2
4  Arizona  1973                58.4     -1.4

In [11]:
# Importing AZ CO2 Fossil Fuel Totals as DF
df_file = pd.read_sql('SELECT * FROM AZ_CO2_FOSSIL_FUEL_TOTALS', engine)

In [12]:
df_file.head()

state  year  coal  petroleum_products  natural_gas
0    State  Year  Coal  Petroleum Products  Natural Gas
1  Arizona  1970   0.8                13.4         10.7
2  Arizona  1971   0.8                14.3         11.8
3  Arizona  1972   0.7                16.8         12.6
4  Arizona  1973   0.9                21.7         11.8

In [13]:
df_population = pd.read_sql('SELECT * FROM AZ_population', engine)

In [14]:
df_population.head()


year  populuation growth_rate
0  Year  Growth Rate  Population
1   1970        2.21%   1,775,399
2   1971        6.78%   1,895,814
3   1972        5.93%   2,008,291
4   1973        5.78%   2,124,438

In [15]:
df_population = df_population.drop(columns = 'populuation')

In [16]:
df_population = df_population.drop(df_population.index[0])

In [17]:
df_population.head()

year growth_rate
1  1970   1,775,399
2  1971   1,895,814
3  1972   2,008,291
4  1973   2,124,438
5  1974   2,223,196

In [18]:
df_population = df_population.rename(columns = {'growth_rate':'population'})

In [19]:
df_population.head()

year population
1  1970  1,775,399
2  1971  1,895,814
3  1972  2,008,291
4  1973  2,124,438
5  1974  2,223,196

In [20]:
year_population = df_population['population'].replace(',', '', regex=True)
year_population.head()

1    1775399
2    1895814
3    2008291
4    2124438
5    2223196
Name: population, dtype: object

In [21]:
year_population = pd.DataFrame(year_population, columns = ['population'])
year_population.head()

population
1    1775399
2    1895814
3    2008291
4    2124438
5    2223196

In [22]:
# GDP from https://countryeconomy.com/gdp/usa-states/arizona
df_gdp = pd.read_sql('SELECT * FROM AZGDP', engine)
df_gdp.head()

year  annual_gdp_in_millions
0  Year  Annual GDP in Millions
1   1970                 $8,569M
2   1971                 $9,649M
3   1972                $11,292M
4   1973                $13,330M

In [23]:
df_gdp = df_gdp.drop(df_gdp.index[0])

In [24]:
df_gdp.head()

year annual_gdp_in_millions
1  1970                $8,569M
2  1971                $9,649M
3  1972               $11,292M
4  1973               $13,330M
5  1974               $14,611M

In [25]:
gdp = df_gdp['annual_gdp_in_millions'].replace('M', '', regex=True)
gdp.head()

1     $8,569
2     $9,649
3    $11,292
4    $13,330
5    $14,611
Name: annual_gdp_in_millions, dtype: object

In [26]:
gdp = gdp.replace(',', '', regex=True)
gdp.head()

1     $8569
2     $9649
3    $11292
4    $13330
5    $14611
Name: annual_gdp_in_millions, dtype: object

In [27]:
gdp= pd.DataFrame(gdp, columns = ['annual_gdp_in_millions'])
gdp.head()

annual_gdp_in_millions
1                  $8569
2                  $9649
3                 $11292
4                 $13330
5                 $14611

In [28]:
df_gdp = df_gdp.drop(columns = 'annual_gdp_in_millions')
df_gdp.head()

year
1  1970
2  1971
3  1972
4  1973
5  1974

In [29]:
gdp_dataframes = [df_gdp, gdp]
gdp.head()

annual_gdp_in_millions
1                  $8569
2                  $9649
3                 $11292
4                 $13330
5                 $14611

In [30]:
gdp_df = pd.concat(
    [
        df_gdp.reset_index(drop=True),
        gdp.reset_index(drop=True),
    ],
    axis=1,
    ignore_index=True,
)

In [31]:
gdp_df.head()

0       1
0  1970   $8569
1  1971   $9649
2  1972  $11292
3  1973  $13330
4  1974  $14611

In [32]:
gdp_df.head()

0       1
0  1970   $8569
1  1971   $9649
2  1972  $11292
3  1973  $13330
4  1974  $14611

In [33]:
gdp_df = gdp_df.rename(columns = {0:'Year', 1:'annual_gdp_in_millions'})
gdp_df.head()

Year annual_gdp_in_millions
0  1970                  $8569
1  1971                  $9649
2  1972                 $11292
3  1973                 $13330
4  1974                 $14611

In [34]:
gdp_df = gdp_df.rename(columns = {'Year':'year'})
gdp_df.head()

year annual_gdp_in_millions
0  1970                  $8569
1  1971                  $9649
2  1972                 $11292
3  1973                 $13330
4  1974                 $14611

In [35]:
dataframes = [df_population, year_population]


In [36]:
df_population = pd.concat(dataframes)

In [37]:
df_population.head()

year population
1  1970  1,775,399
2  1971  1,895,814
3  1972  2,008,291
4  1973  2,124,438
5  1974  2,223,196

In [38]:
df = df.drop(columns = 'state')
df.head()

year  degrees_fahrenheit  anomaly
0  Year  Degrees Fahrenheit  Anomaly
1  1970                  59     -0.8
2  1971                58.2     -1.6
3  1972                59.6     -0.2
4  1973                58.4     -1.4

In [39]:
df_file = df_file.drop(columns = 'state')

In [40]:
df_file.head()

year  coal  petroleum_products  natural_gas
0  Year  Coal  Petroleum Products  Natural Gas
1  1970   0.8                13.4         10.7
2  1971   0.8                14.3         11.8
3  1972   0.7                16.8         12.6
4  1973   0.9                21.7         11.8

In [41]:
df = pd.merge(df, df_file, on = 'year')
df = pd.merge(df, df_population, on = 'year')

df.head()

year degrees_fahrenheit anomaly coal petroleum_products natural_gas  \
0  1970                 59    -0.8  0.8               13.4        10.7   
1  1971               58.2    -1.6  0.8               14.3        11.8   
2  1972               59.6    -0.2  0.7               16.8        12.6   
3  1973               58.4    -1.4  0.9               21.7        11.8   
4  1974               59.5    -0.3  4.6               21.4        10.7   

  population  
0  1,775,399  
1  1,895,814  
2  2,008,291  
3  2,124,438  
4  2,223,196

In [42]:
df = pd.merge(df, gdp_df, on = 'year')
df.head()

year degrees_fahrenheit anomaly coal petroleum_products natural_gas  \
0  1970                 59    -0.8  0.8               13.4        10.7   
1  1971               58.2    -1.6  0.8               14.3        11.8   
2  1972               59.6    -0.2  0.7               16.8        12.6   
3  1973               58.4    -1.4  0.9               21.7        11.8   
4  1974               59.5    -0.3  4.6               21.4        10.7   

  population annual_gdp_in_millions  
0  1,775,399                  $8569  
1  1,895,814                  $9649  
2  2,008,291                 $11292  
3  2,124,438                 $13330  
4  2,223,196                 $14611

In [43]:
df = df.drop(columns = 'anomaly')

In [44]:
df['population'] = df['population'].str.replace(',','')

In [45]:
df['annual_gdp_in_millions'] = df['annual_gdp_in_millions'].str.replace('$','')

In [46]:
df.head()

year degrees_fahrenheit coal petroleum_products natural_gas population  \
0  1970                 59  0.8               13.4        10.7    1775399   
1  1971               58.2  0.8               14.3        11.8    1895814   
2  1972               59.6  0.7               16.8        12.6    2008291   
3  1973               58.4  0.9               21.7        11.8    2124438   
4  1974               59.5  4.6               21.4        10.7    2223196   

  annual_gdp_in_millions  
0                   8569  
1                   9649  
2                  11292  
3                  13330  
4                  14611

In [47]:
df.columns

Index(['year', 'degrees_fahrenheit', 'coal', 'petroleum_products',
       'natural_gas', 'population', 'annual_gdp_in_millions'],
      dtype='object')

In [48]:
X = df[['year', 'coal', 'petroleum_products',
       'natural_gas', 'population','annual_gdp_in_millions']].copy()

X = X.dropna()
y=df['degrees_fahrenheit']
X.head()

year coal petroleum_products natural_gas population annual_gdp_in_millions
0  1970  0.8               13.4        10.7    1775399                   8569
1  1971  0.8               14.3        11.8    1895814                   9649
2  1972  0.7               16.8        12.6    2008291                  11292
3  1973  0.9               21.7        11.8    2124438                  13330
4  1974  4.6               21.4        10.7    2223196                  14611

In [49]:
X = X.drop(X.index[0])
X.head()

year coal petroleum_products natural_gas population annual_gdp_in_millions
1  1971  0.8               14.3        11.8    1895814                   9649
2  1972  0.7               16.8        12.6    2008291                  11292
3  1973  0.9               21.7        11.8    2124438                  13330
4  1974  4.6               21.4        10.7    2223196                  14611
5  1975  8.8               20.8         8.6    2284847                  15284

In [50]:
y = y.drop(y.index[0])

In [51]:
X.corr()

Empty DataFrame
Columns: []
Index: []

In [52]:
X.dropna()
X.tail()

year  coal petroleum_products natural_gas population  \
45  2015  36.9               38.8        19.3    6832810   
46  2016  30.9               40.2        19.7    6944767   
47  2017  32.0               40.8        17.7    7048088   
48  2018  31.7               41.2        21.1    7164228   
49  2019  24.6               42.3        25.6    7291843   

   annual_gdp_in_millions  
45                 299393  
46                 313081  
47                 330416  
48                 349908  
49                 369988

In [53]:
X.dtypes

year                      object
coal                      object
petroleum_products        object
natural_gas               object
population                object
annual_gdp_in_millions    object
dtype: object

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 42)

In [55]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# Fitting our model with all our features in X
model.fit(X_train, y_train)

score = model.score(X, y)
print(f"R2 Score: {score}")

R2 Score: 0.5542171665625955


In [56]:
scaler = MinMaxScaler()

In [57]:
scaler.fit(X_train)

MinMaxScaler()

In [58]:
X_train_scaled = scaler.transform(X_train)

In [59]:
X_test_scaled = scaler.transform(X_test)

In [60]:
# Random Forest
rf_model = RandomForestRegressor(n_estimators=128, random_state=78)

In [61]:
rf = rf_model.fit(X_train_scaled, y_train)

In [62]:
rf_predictions = rf_model.predict(X_test_scaled)

In [63]:
predictions = pd.DataFrame({"Predictions":rf_predictions, "Actual":y_test})

In [64]:
predictions.head(25)

Predictions Actual
14    59.614844   59.4
46    61.740625   62.2
48    61.588281   62.3
45    61.525781   61.8
18    59.679688   60.2
28    60.914063   59.3
27    60.749219   60.5
26    60.695313   61.9
32    61.437500   61.2
20    59.564844   59.7
13    59.833594   59.2
5     59.449219   57.9
35    61.203906   61.1

In [65]:
rf.score(X_test_scaled, y_test)

0.6386318260360727

In [66]:
y_train

9     58.8
4     59.5
7     60.2
41    60.3
42    62.1
47      63
16    60.6
10    60.2
17    59.3
25      61
34    60.4
31    61.2
1     58.2
44    62.2
33    61.9
6       59
30    61.7
12    58.7
37    61.6
2     59.6
22    59.6
3     58.4
38    60.6
36    61.1
24    60.6
40    60.4
11    61.3
23    59.8
19    61.2
49    60.3
21    59.2
8     59.8
43    60.4
15    59.6
29    60.8
39    61.1
Name: degrees_fahrenheit, dtype: object

In [67]:
y_pred = model.predict(X_test_scaled)

In [68]:
y_pred

array([451.48929956, 451.29083057, 451.27401048, 451.29814984,
       451.47531722, 451.43770894, 451.44737038, 451.45499459,
       451.39194293, 451.46778744, 451.49326262, 451.50290783,
       451.3559395 ])

In [69]:
df.columns

Index(['year', 'degrees_fahrenheit', 'coal', 'petroleum_products',
       'natural_gas', 'population', 'annual_gdp_in_millions'],
      dtype='object')

In [89]:

test = pd.DataFrame({'Year':[2050],
       'Coal':[30], 'Petroleum Products':[40],
       'Natural Gas':[25],'population':[10000000], 'annual_gdp_in_millions':[420000]})


In [90]:
model.predict(test)

array([59.04923118])

In [72]:
df.corr()

Empty DataFrame
Columns: []
Index: []

In [73]:
from sklearn.linear_model import LinearRegression
classifier = LinearRegression(fit_intercept = True, normalize = False)
classifier

LinearRegression(normalize=False)

In [74]:
classifier.fit(X_train_scaled, y_train)

LinearRegression(normalize=False)

In [75]:
X_train_scaled

array([[0.16666667, 0.52546296, 0.32142857, 0.195     , 0.13709285,
        0.04952559],
       [0.0625    , 0.09027778, 0.25357143, 0.255     , 0.06067091,
        0.01377037],
       [0.125     , 0.37962963, 0.35357143, 0.18      , 0.09810603,
        0.02764064],
       [0.83333333, 1.        , 0.85357143, 0.495     , 0.84832791,
        0.69730726],
       [0.85416667, 0.91435185, 0.82142857, 0.615     , 0.86369625,
        0.72651309],
       [0.95833333, 0.72453704, 0.94642857, 0.605     , 0.95482697,
        0.89018119],
       [0.3125    , 0.63425926, 0.29642857, 0.        , 0.26175693,
        0.12830141],
       [0.1875    , 0.52314815, 0.21785714, 0.175     , 0.15603326,
        0.0585976 ],
       [0.33333333, 0.60648148, 0.31428571, 0.04      , 0.28563394,
        0.13986274],
       [0.5       , 0.73842593, 0.46785714, 0.055     , 0.44682747,
        0.27822967],
       [0.6875    , 0.92592593, 0.83928571, 0.665     , 0.69617676,
        0.54640769],
       [0.625     , 0

In [76]:
type(y_train)

pandas.core.series.Series

In [77]:
predictions = classifier.predict(X_test_scaled)
pd.DataFrame({"Prediction": predictions, "Actual": y_test})

Prediction Actual
14   59.931351   59.4
46   61.194293   62.2
48   61.428826   62.3
45   61.165559   61.8
18   60.074519   60.2
28   60.884784   59.3
27   60.849892   60.5
26   60.765419   61.9
32   61.046612   61.2
20   59.990730   59.7
13   59.868599   59.2
5    59.586651   57.9
35   61.256416   61.1

In [78]:
classifier.score(X_test_scaled,y_test)

0.5628716803664418

In [79]:
from sklearn.linear_model import Ridge

In [80]:
ridge = Ridge(alpha = 1, solver = 'auto')

In [81]:
ridge.fit(X_train_scaled, y_train)

Ridge(alpha=1)

In [82]:
ridge.score(X_test_scaled, y_test)

0.6029343393094474

In [83]:
ridge.predict(X_test_scaled)

array([59.91131707, 61.27275281, 61.38014522, 61.28785149, 60.05800212,
       60.64440058, 60.5508715 , 60.48494069, 60.88319097, 60.14705368,
       59.82131115, 59.37227018, 61.0713201 ])